-- V41: Add per-lesson configurable settings (activity formats, streak thresholds, retry/demotion limits)

ALTER TABLE lessons
    ADD COLUMN IF NOT EXISTS module2_activities TEXT DEFAULT 'MULTIPLE_CHOICE;FILL_IN_BLANK;MATCHING;WORD_SCRAMBLE;IMAGE_LABELING;TRUE_OR_FALSE',
    ADD COLUMN IF NOT EXISTS module3_activities TEXT DEFAULT 'SENTENCE_COMPLETION;SENTENCE_ARRANGEMENT;PRONUNCIATION_FEEDBACK',
    ADD COLUMN IF NOT EXISTS module4_activities TEXT DEFAULT 'IMAGE_MATCHING;FILL_IN_BLANK;SENTENCE_RECONSTRUCTION',
    ADD COLUMN IF NOT EXISTS upgrade_streak_required INT DEFAULT 2,
    ADD COLUMN IF NOT EXISTS demotion_threshold INT DEFAULT 2,
    ADD COLUMN IF NOT EXISTS reintroduction_threshold INT DEFAULT 4;
