-- Migration V61: Add module4_activities to vocabulary_categories
ALTER TABLE vocabulary_categories
    ADD COLUMN IF NOT EXISTS module4_activities VARCHAR(500) DEFAULT 'MULTIPLE_CHOICE;MATCHING;FILL_IN_BLANK;WORD_SCRAMBLE;SENTENCE_RECONSTRUCTION;TRUE_OR_FALSE';

UPDATE vocabulary_categories
SET module4_activities = 'MULTIPLE_CHOICE;MATCHING;FILL_IN_BLANK;WORD_SCRAMBLE;SENTENCE_RECONSTRUCTION;TRUE_OR_FALSE'
WHERE module4_activities IS NULL;
