server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.application.name=vocaboo-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pqqpzsqkcgprucarqpcl
spring.datasource.password=QNQIcLQSS4pg9qkY

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:vocaboo_super_secret_signing_key_must_be_long_enough_to_meet_security_requirements}
app.jwt.expiration-ms=86400000



